version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["A2-insubstantial", "B0-silent", "C1-low 📌"]
    # Handle updates for crates from github.com/axiatech/substrate manually.
    ignore:
      - dependency-name: "substrate-*"
      - dependency-name: "sc-*"
      - dependency-name: "sp-*"
      - dependency-name: "frame-*"
      - dependency-name: "fork-tree"
      - dependency-name: "remote-externalities"
      - dependency-name: "pallet-*"
      - dependency-name: "beefy-*"
      - dependency-name: "try-runtime-*"
      - dependency-name: "test-runner"
      - dependency-name: "generate-bags"
      - dependency-name: "sub-tokens"
      - dependency-name: "axia-*"
      - dependency-name: "xcm*"
      - dependency-name: "axctest-*"
      - dependency-name: "alphanet-*"
    schedule:
      interval: "daily"
