[package]
name = "allychain-template-node"
version = "0.1.0"
authors = ["Anonymous"]
description = "A new Cumulus FRAME-based Substrate Node, ready for hacking together a allychain."
license = "Unlicense"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/cumulus/"
edition = "2021"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

[[bin]]
name = "allychain-collator"
path = "src/main.rs"

[features]
runtime-benchmarks = [
	"allychain-template-runtime/runtime-benchmarks",
	"axia-cli/runtime-benchmarks",
]
try-runtime = ["allychain-template-runtime/try-runtime"]

[dependencies]
clap = { version = "3.1", features = ["derive"] }
derive_more = "0.99.2"
log = "0.4.14"
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.132", features = ["derive"] }
hex-literal = "0.3.4"

# RPC related Dependencies
jsonrpc-core = "18.0.0"

# Local Dependencies
allychain-template-runtime = { path = "../runtime" }

# Substrate Dependencies
frame-benchmarking = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
frame-benchmarking-cli = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
try-runtime-cli = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

pallet-transaction-payment-rpc = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

substrate-frame-rpc-system = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
substrate-prometheus-endpoint = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

## Substrate Client Dependencies
sc-basic-authorship = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-chain-spec = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-cli = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-client-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-consensus = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-executor = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-network = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-keystore = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-rpc = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-rpc-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-service = { git = "https://github.com/purestake/substrate", features = ["wasmtime"], branch = "moonbeam-axia-v0.9.17" }
sc-telemetry = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-transaction-pool = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-transaction-pool-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sc-tracing = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

## Substrate Primitive Dependencies
sp-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-block-builder = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-blockchain = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-consensus = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-consensus-aura = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-core = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-inherents = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-keystore = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-offchain = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-session = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-timestamp = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }
sp-transaction-pool = { git = "https://github.com/purestake/substrate", branch = "moonbeam-axia-v0.9.17" }

# Cumulus dependencies
cumulus-client-cli = { path = "../../client/cli" }
cumulus-client-collator = { path = "../../client/collator" }
cumulus-client-consensus-aura = { path = "../../client/consensus/aura" }
cumulus-client-consensus-common = { path = "../../client/consensus/common" }
cumulus-client-network = { path = "../../client/network" }
cumulus-client-service = { path = "../../client/service" }
cumulus-primitives-core = { path = "../../primitives/core" }
cumulus-primitives-allychain-inherent = { path = "../../primitives/allychain-inherent" }
cumulus-relay-chain-interface = { path = "../../client/relay-chain-interface" }
cumulus-relay-chain-local = { path = "../../client/relay-chain-local" }

# Axia dependencies
axia-cli = { git = "https://github.com/purestake/axia", branch = "moonbeam-axia-v0.9.17" }
axia-allychain = { git = "https://github.com/purestake/axia", branch = "moonbeam-axia-v0.9.17" }
axia-primitives = { git = "https://github.com/purestake/axia", branch = "moonbeam-axia-v0.9.17" }
axia-service = { git = "https://github.com/purestake/axia", branch = "moonbeam-axia-v0.9.17" }
xcm = { git = "https://github.com/purestake/axia", default-features = false, branch = "moonbeam-axia-v0.9.17" }
