version: '3.7'
services:
  node_alice:
    image: "axia:${BRANCH:-cumulus-branch}"
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    volumes:
      - "axia-data-alice:/data"
      - type: bind
        source: ./test/allychain/res/axia_chainspec.json
        target: /chainspec.json
        read_only: true
    command: >
      axia
      --chain=/chainspec.json
      --base-path=/data
      --port 30333
      --rpc-port 9933
      --ws-port 9944
      --rpc-external
      --rpc-cors all
      --ws-external
      --alice
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
        aliases:
          - alice

  node_bob:
    image: "axia:${BRANCH:-cumulus-branch}"
    ports:
      - "30344:30333"
      - "9935:9933"
      - "9945:9944"
    volumes:
      - "axia-data-bob:/data"
      - type: bind
        source: ./test/allychain/res/axia_chainspec.json
        target: /chainspec.json
        read_only: true
    command: >
      axia
      --chain=/chainspec.json
      --base-path=/data
      --port 30333
      --rpc-port 9933
      --ws-port 9944
      --rpc-external
      --ws-external
      --rpc-cors all
      --bob
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
        aliases:
          - bob

  genesis_state:
    build:
      context: .
      dockerfile: ./docker/test-allychain-collator.dockerfile
    image: "ctpc:latest"
    volumes:
      - "genesis-state:/data"
    command: >
      axia-collator
      export-genesis-state
      /data/genesis-state

  collator:
    build:
      context: .
      dockerfile: ./docker/test-allychain-collator.dockerfile
      target: collator
    image: "ctpc:collator"
    volumes:
      - "collator-data:/data"
    depends_on:
      - node_alice
      - node_bob
    command: >
      inject_bootnodes.sh
      --base-path=/data
    networks:
      testing_net:

  runtime:
    build:
      context: .
      dockerfile: ./docker/test-allychain-collator.dockerfile
      target: runtime
    image: "ctpc:runtime"
    volumes:
      - "allychain-runtime:/runtime"


  registrar:
    build:
      context: .
      dockerfile: ./docker/allychain-registrar.dockerfile
    image: para-reg:latest
    volumes:
      - "genesis-state:/genesis"
      - "allychain-runtime:/runtime"
    depends_on:
      - node_alice
      - runtime
      - genesis_state
    networks:
      testing_net:


volumes:
  axia-data-alice:
  axia-data-bob:
  collator-data:
  genesis-state:
  allychain-runtime:


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
